name: Docker Build and Push to DockerHub
env:
  DOCKER_CLI_EXPERIMENTAL: enabled

on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    name: Build and push graphmindset image
    steps:
      - name: Check out from Git
        uses: actions/checkout@v4
      - name: Set release tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
      - name: Run Docker buildx
        run: |
          docker buildx build \
          --no-cache \
          --platform linux/amd64 \
          --tag "${{ secrets.DOCKER_HUB_USER }}/graphmindset:${{ env.RELEASE_TAG }}" \
          --tag "${{ secrets.DOCKER_HUB_USER }}/graphmindset:latest" \
          --output "type=registry" ./
